// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Proto struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Op                   int32    `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Seq                  int32    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_cc76ce5b07a370a0, []int{0}
}
func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (dst *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(dst, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *Proto) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_cc76ce5b07a370a0, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PushMsgReq struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ProtoOp              int32    `protobuf:"varint,3,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_cc76ce5b07a370a0, []int{2}
}
func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (dst *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(dst, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PushMsgReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *PushMsgReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type PushMsgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_cc76ce5b07a370a0, []int{3}
}
func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (dst *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(dst, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

type BroadcastReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_cc76ce5b07a370a0, []int{4}
}
func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (dst *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(dst, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *BroadcastReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type BroadcastReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReply) Reset()         { *m = BroadcastReply{} }
func (m *BroadcastReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastReply) ProtoMessage()    {}
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_cc76ce5b07a370a0, []int{5}
}
func (m *BroadcastReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReply.Unmarshal(m, b)
}
func (m *BroadcastReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReply.Marshal(b, m, deterministic)
}
func (dst *BroadcastReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReply.Merge(dst, src)
}
func (m *BroadcastReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastReply.Size(m)
}
func (m *BroadcastReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Proto)(nil), "ctpf.comet.Proto")
	proto.RegisterType((*Empty)(nil), "ctpf.comet.Empty")
	proto.RegisterType((*PushMsgReq)(nil), "ctpf.comet.PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "ctpf.comet.PushMsgReply")
	proto.RegisterType((*BroadcastReq)(nil), "ctpf.comet.BroadcastReq")
	proto.RegisterType((*BroadcastReply)(nil), "ctpf.comet.BroadcastReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_cc76ce5b07a370a0) }

var fileDescriptor_api_cc76ce5b07a370a0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x9a, 0x9a, 0x28, 0x47, 0x55, 0x95, 0x1b, 0x90, 0x95, 0xa9, 0xca, 0x42, 0x07, 0xc8,
	0x50, 0x46, 0x26, 0x5a, 0x31, 0x30, 0xa0, 0x06, 0x8f, 0x6c, 0x69, 0x62, 0x42, 0x44, 0x8a, 0xaf,
	0x71, 0x8a, 0xe4, 0xff, 0xe5, 0x43, 0x50, 0x9c, 0x36, 0x34, 0x02, 0xa4, 0x6e, 0xcf, 0xef, 0x9e,
	0xef, 0xbd, 0x7b, 0xe0, 0x27, 0x54, 0x44, 0x54, 0xa9, 0x5a, 0x21, 0xa4, 0x35, 0xbd, 0x46, 0xa9,
	0xda, 0xc8, 0x3a, 0x5c, 0x01, 0x8b, 0x2d, 0x39, 0x01, 0xf7, 0x53, 0x56, 0xdc, 0x99, 0x3a, 0x33,
	0x26, 0x1a, 0x88, 0x63, 0x18, 0x28, 0xe2, 0x03, 0x4b, 0x0c, 0x14, 0x35, 0x0a, 0x2d, 0xb7, 0xdc,
	0x6d, 0x15, 0x5a, 0x6e, 0x11, 0x61, 0xb8, 0x56, 0x99, 0xe1, 0xc3, 0xa9, 0x33, 0x1b, 0x09, 0x8b,
	0x43, 0x0f, 0xd8, 0xc3, 0x86, 0x6a, 0x13, 0xa6, 0x00, 0xf1, 0x4e, 0xbf, 0x3d, 0xe9, 0x5c, 0xb4,
	0xd2, 0x77, 0x69, 0x34, 0x77, 0xa6, 0xee, 0xcc, 0x17, 0x16, 0x23, 0x07, 0xcf, 0x06, 0x5a, 0xd1,
	0x7e, 0xe9, 0xe1, 0x89, 0x57, 0xc0, 0x2c, 0xb4, 0xee, 0xe7, 0xf3, 0x8b, 0xe8, 0x27, 0x71, 0x64,
	0xe3, 0x8a, 0x76, 0x1e, 0x8e, 0x61, 0xd4, 0x99, 0x50, 0x69, 0xc2, 0x67, 0x18, 0x2d, 0x2a, 0x95,
	0x64, 0x69, 0xa2, 0xeb, 0xc6, 0x96, 0x83, 0x97, 0x57, 0x6a, 0x47, 0x8f, 0x99, 0xbd, 0xcc, 0x17,
	0x87, 0xe7, 0xe9, 0x16, 0x13, 0x18, 0x1f, 0xad, 0xa4, 0xd2, 0xcc, 0xbf, 0x1c, 0x60, 0xcb, 0x46,
	0x88, 0xd7, 0x30, 0x8c, 0x8b, 0x8f, 0x1c, 0x7b, 0xbf, 0xed, 0xf9, 0xc1, 0x6f, 0x0a, 0x6f, 0x80,
	0x2d, 0x4b, 0xa5, 0xe5, 0x89, 0xf2, 0x3b, 0xf0, 0xf6, 0xb7, 0xe1, 0x65, 0x2f, 0x5d, 0xd7, 0x6a,
	0xc0, 0xff, 0xe4, 0xa9, 0x34, 0x78, 0x0f, 0x7e, 0x97, 0x1a, 0x7b, 0xb2, 0xe3, 0x7e, 0x82, 0xe0,
	0x9f, 0x09, 0x95, 0x66, 0xc1, 0x5e, 0xdc, 0x84, 0x8a, 0xf5, 0x99, 0xad, 0xe1, 0xf6, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x94, 0xe4, 0x43, 0xbc, 0x41, 0x02, 0x00, 0x00,
}
